# Generated by Django 4.0.8 on 2024-02-29 16:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_managers_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pictures/%y/%m/%d/'),
        ),
    ]
