# Generated by Django 4.0.8 on 2024-03-22 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLecturerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lectures_list/', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'])])),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
